### ISSUE TITLE
Reproductibility netzoo python/matlab

### ISSUE THREAD

**Issue by maudf** [netZoo/netZooPy#295] opened 2022-12-06 08:43 UTC
Using the 0.9.11 version of netzoopy (conda), I still have marginal differences between results I obtain from matlab and netzoopy PANDA and LIONESS. This may be due to different defaultways of including genes absent from the prior but present in the expression matrix . I have overall very good correlations between matlab and netzoopy results, both with panda and lioness. I have good Spearman's correlation coefficients between matlab and netzoopy results for my dataset (>0.96), which contains 66 samples, and about 106 TFBS and 32,165 genes. 
When I compare matlab and netzoopy results for PANDA I have : 
max(abs(network1-network2))=1.05436 (but 3rd quartile is 0.021781)
And the same for LIONESS:
max(abs(network1-network2))=31.80962 (but 3rd quartile is 0.05113)
So this is really afew edge cases.
I can send the data through fileShare, but they are too heavy (and confidential) to be uploaded here :-).

**Comment by violafanfani** [comment] 2022-12-07 22:33
Dear @maudf I think we can start by debugging with test/non confidential data. Can you send an email to vfanfani@hsph.harvard.edu with the calls (PANDA and LIONESS) for both MATLAB and netzoopy? I am gonna try to reproduce the error with exactly the same parameters.

**Comment by violafanfani** [comment] 2023-05-26 15:43
I am gonna close this because there has been no action for a while. Feel free to reopen once it becomes relevant again.

**Closed by violafanfani** 2023-05-26 15:43 UTC
